import { collection, addDoc } from 'firebase/firestore';
import { db } from '../firebase/config';

const sampleProducts = [
  {
    name: 'Classic White T-Shirt',
    description: 'Essential cotton t-shirt perfect for everyday wear',
    price: 24.99,
    category: 'T-Shirts',
    stock: 50,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White'],
    images: ['https://example.com/white-tshirt.jpg'],
  },
  {
    name: 'Slim Fit Jeans',
    description: 'Modern slim fit jeans in dark wash',
    price: 79.99,
    category: 'Jeans',
    stock: 35,
    sizes: ['30x32', '32x32', '34x32', '36x32'],
    colors: ['Dark Blue'],
    images: ['https://example.com/slim-jeans.jpg'],
  },
  {
    name: 'Leather Jacket',
    description: 'Classic leather jacket with modern details',
    price: 199.99,
    category: 'Outerwear',
    stock: 15,
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Brown'],
    images: ['https://example.com/leather-jacket.jpg'],
  },
  {
    name: 'Running Shoes',
    description: 'Lightweight running shoes with cushioned sole',
    price: 89.99,
    category: 'Footwear',
    stock: 40,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['Black/White', 'Blue/Gray'],
    images: ['https://example.com/running-shoes.jpg'],
  },
  {
    name: 'Hooded Sweatshirt',
    description: 'Comfortable cotton blend hoodie',
    price: 49.99,
    category: 'Hoodies',
    stock: 45,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Gray', 'Black', 'Navy'],
    images: ['https://example.com/hoodie.jpg'],
  },
  {
    name: 'Chino Pants',
    description: 'Classic chino pants in stretch cotton',
    price: 59.99,
    category: 'Pants',
    stock: 30,
    sizes: ['30x32', '32x32', '34x32', '36x32'],
    colors: ['Khaki', 'Navy', 'Olive'],
    images: ['https://example.com/chinos.jpg'],
  },
  {
    name: 'Polo Shirt',
    description: 'Classic polo shirt in premium cotton',
    price: 39.99,
    category: 'Shirts',
    stock: 55,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'White', 'Light Blue'],
    images: ['https://example.com/polo.jpg'],
  },
  {
    name: 'Denim Jacket',
    description: 'Classic denim jacket with button closure',
    price: 89.99,
    category: 'Outerwear',
    stock: 25,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Light Blue', 'Dark Blue'],
    images: ['https://example.com/denim-jacket.jpg'],
  },
  {
    name: 'Athletic Shorts',
    description: 'Lightweight athletic shorts with pockets',
    price: 29.99,
    category: 'Shorts',
    stock: 60,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Gray', 'Navy'],
    images: ['https://example.com/athletic-shorts.jpg'],
  },
  {
    name: 'Dress Shirt',
    description: 'Classic fit dress shirt in wrinkle-resistant cotton',
    price: 69.99,
    category: 'Shirts',
    stock: 40,
    sizes: ['15/32', '15.5/33', '16/33', '16.5/34'],
    colors: ['White', 'Light Blue', 'Pink'],
    images: ['https://example.com/dress-shirt.jpg'],
  },
  {
    name: 'Winter Coat',
    description: 'Warm winter coat with faux fur hood',
    price: 149.99,
    category: 'Outerwear',
    stock: 20,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy'],
    images: ['https://example.com/winter-coat.jpg'],
  },
  {
    name: 'Cargo Shorts',
    description: 'Durable cargo shorts with multiple pockets',
    price: 44.99,
    category: 'Shorts',
    stock: 35,
    sizes: ['30', '32', '34', '36'],
    colors: ['Khaki', 'Olive', 'Gray'],
    images: ['https://example.com/cargo-shorts.jpg'],
  },
  {
    name: 'V-Neck Sweater',
    description: 'Classic v-neck sweater in soft wool blend',
    price: 79.99,
    category: 'Sweaters',
    stock: 30,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Gray', 'Burgundy'],
    images: ['https://example.com/v-neck-sweater.jpg'],
  },
  {
    name: 'Canvas Sneakers',
    description: 'Classic canvas sneakers for casual wear',
    price: 49.99,
    category: 'Footwear',
    stock: 45,
    sizes: ['7', '8', '9', '10', '11'],
    colors: ['White', 'Black', 'Navy'],
    images: ['https://example.com/canvas-sneakers.jpg'],
  },
  {
    name: 'Swim Trunks',
    description: 'Quick-dry swim trunks with mesh lining',
    price: 34.99,
    category: 'Swimwear',
    stock: 40,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Red', 'Black'],
    images: ['https://example.com/swim-trunks.jpg'],
  },
  {
    name: 'Blazer',
    description: 'Modern fit blazer in wool blend',
    price: 159.99,
    category: 'Suits',
    stock: 25,
    sizes: ['38R', '40R', '42R', '44R'],
    colors: ['Navy', 'Gray', 'Black'],
    images: ['https://example.com/blazer.jpg'],
  },
  {
    name: 'Baseball Cap',
    description: 'Classic baseball cap with adjustable strap',
    price: 24.99,
    category: 'Accessories',
    stock: 75,
    sizes: ['One Size'],
    colors: ['Black', 'Navy', 'Gray', 'Red'],
    images: ['https://example.com/baseball-cap.jpg'],
  },
  {
    name: 'Dress Socks',
    description: 'Premium cotton dress socks, pack of 3',
    price: 19.99,
    category: 'Accessories',
    stock: 100,
    sizes: ['One Size'],
    colors: ['Black', 'Navy', 'Gray'],
    images: ['https://example.com/dress-socks.jpg'],
  },
  {
    name: 'Belt',
    description: 'Genuine leather belt with silver buckle',
    price: 39.99,
    category: 'Accessories',
    stock: 50,
    sizes: ['32', '34', '36', '38', '40'],
    colors: ['Black', 'Brown'],
    images: ['https://example.com/belt.jpg'],
  },
  {
    name: 'Wallet',
    description: 'Slim leather wallet with card slots',
    price: 29.99,
    category: 'Accessories',
    stock: 60,
    sizes: ['One Size'],
    colors: ['Black', 'Brown'],
    images: ['https://example.com/wallet.jpg'],
  }
];

export async function addSampleProducts() {
  const productsRef = collection(db, 'products');
  
  try {
    for (const product of sampleProducts) {
      await addDoc(productsRef, {
        ...product,
        createdAt: new Date().toISOString(),
      });
    }
    return { success: true, message: 'Sample products added successfully' };
  } catch (error) {
    console.error('Error adding sample products:', error);
    return { success: false, message: 'Failed to add sample products' };
  }
} 